services:
  streaming-server:
    image: stt-model-server
    container_name: stt-model-server
    environment:
      PY_ENV: prod
      MODEL_SIZE: base
      MODEL_COMPUTE_TYPE: int8
      SEG_TERM_TIME_MS: "1000"
      SEG_RELOCATION: "true"
      APP_PORT: "8080"
      APP_HOST: 0.0.0.0
      APP_SRC_PATH: /mnt/src
      APP_DST_PATH: /mnt/out
    volumes:
      - ../dev/src:/mnt/src
      - ../dev/out:/mnt/out
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
