services:
  streaming-server:
    image: stt-model-server
    container_name: stt-model-server
    environment:
      PY_ENV: prod
      APP_PORT: "8080"
      APP_HOST: 0.0.0.0
      APP_MODEL_TYPE: base
      APP_COMPUTE_TYPE: int8
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
