services:
  streaming-server:
    image: stt-model-server
    container_name: stt-model-server
    environment:
      PY_ENV: prod
      MODEL_SIZE: large-v3
      MODEL_COMPUTE_TYPE: int8
      SEG_TERM_TIME_MS: "500"
      SEG_PER_CHAR_MS: "50"
      SEG_RELOCATION: "true"
      APP_PORT: "8080"
      APP_HOST: 0.0.0.0
      APP_SRC_PATH: /mnt/volume/src
      APP_DST_PATH: /mnt/volume/out
    volumes:
      - /mnt/nas/stt:/mnt/volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
