services:
  streaming-server:
    image: stt-model-server
    container_name: stt-model-server
    environment:
      PY_ENV: prod
      APP_PORT: "8080"
      APP_HOST: 0.0.0.0
      APP_MODEL_TYPE: large-v2
      APP_COMPUTE_TYPE: int8
      APP_SRC_PATH: /mnt/volume/src
      APP_DST_PATH: /mnt/volume/out
    volumes:
      - /mnt/nas/stt:/mnt/volume
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
